name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: |
          pwd
          echo "GITHUB_WORKSPACE : ${GITHUB_WORKSPACE}"
          cd ..
          echo "after cd .."
          pwd
          echo "step2 ended"
        
      - name: my-step2
        run: |
          echo "second step"
          pwd
          echo "GITHUB_WORKSPACE : ${GITHUB_WORKSPACE}"
          cd ..
          echo "after cd .."
          pwd
