name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: |
          pwd
          echo "GITHUB_REPO : ${GITHUB_WORKSPACE}"
          cd..
          pwd
          echo "step2 ended"
        
      - name: my-step2
        run: |
          pwd
          echo "GITHUB_REPO : ${GITHUB_WORKSPACE}"
          pwd
