name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: |
          echo "GITHUB_REPO : ${GITHUB_REPOSITORY#*/}"
          echo "GITHUB_REPO with std: ${GITHUB_REF#refs/heads/}"
          echo "GITHUB_BRANCH without name: ${{ github.ref }}"
          echo "GITHUB_BRANCH with name: ${{ github.ref_name }}"
          
          
